//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_detail
    {
        public int id { get; set; }
        public int title_id { get; set; }
        public int shift_id { get; set; }
        public int status_id { get; set; }
        public int employee_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee_status Employee_status { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Title Title { get; set; }
    }
}
