//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_detail
    {
        public int id { get; set; }
        public int sale_id { get; set; }
        public int product_id { get; set; }
        public int quantity { get; set; }
        public int payment_type_id { get; set; }
        public int payment_status_id { get; set; }
    
        public virtual Payment_status Payment_status { get; set; }
        public virtual Payment_type Payment_type { get; set; }
        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
